### PR TITLE
Imported https://code.google.com/archive/p/opensmiles/ golang parser.

### PR DESCRIPTION
**Pull request by snakeru**
This is a Golang parser that I wrote a few years ago. The license choice is discussable, I don't have any strong preferences.

### CODE REVIEW

**Comment by johnmay** [comment]
I think this is better hosted elsewhere (i.e. the google code page), we can then link out to it as an example parser.

**Comment by snakeru** [comment]
That could also be done. However, consider this:

1) when implementing this library I encountered a problem with the format definition: there was an ambiguity in one place that could have only been solved by putting some (pretty minor, but still) logic into a lexer (not parser)
2) the format specification on the opensmiles.org is the html page while this library includes an .y file that is known to correctly compile so the parsers for other languages could use it as a reference point (by copy-pasting and replacing the language-specific parts).

So I think that while an 'example parser' should live in an external repository, a 'reference parser' should probably be the part of the standard or at least some key part of it. So if you are opposed to including the whole thing - may be we should still include the yacc (.y) file?

**Comment by baoilleach** [comment]
I'd be opposed to including the entire codebase myself and I'd encourage you to check it into a separate repository. But adding pointers to implementations, particularly clean ones, would be a good idea. And links to yacc files.

If the format definition has some problems, we'd appreciate if you could file an issue against it or submit a pull request.

**Comment by johnmay** [comment]
Any thoughts @ghutchis @egonw @timvdm? Just been discussing with Noel in the office (he's evaluating all the different SMILES handling ATM and I remember this one) - I think I'm most of favour of linking to various implementations in other repos.

[RDKit/smiles.yy](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/SmilesParse/smiles.yy)
[CDK/Beam/Parser.java](https://github.com/johnmay/beam/blob/master/core/src/main/java/uk/ac/ebi/beam/Parser.java)
[OpenBabel/smilesformat.ccp](https://github.com/openbabel/openbabel/blob/master/src/formats/smilesformat.cpp)
[OpenBabel/smiley.h](https://github.com/openbabel/openbabel/blob/master/src/formats/smiley.h)
[ChemF/SmilesParser.scala](https://github.com/stefan-hoeck/chemf/blob/master/src/main/scala/chemf/parser/SmilesParser.scala)
[Radium/Smiles.hs](https://github.com/klangner/radium/blob/master/src/Radium/Formats/Smiles.hs)
[Ouch/Smiles.hs](https://github.com/odj/Ouch/blob/master/Ouch/Input/Smiles.hs)
[chemkit/smileslineformat.cpp](https://github.com/kylelutz/chemkit/blob/master/src/plugins/smiles/smileslineformat.cpp)
[PerlMol/](https://sourceforge.net/p/perlmol/code/)

**Comment by ghutchis** [comment]
Yes, linking is fine.

**Comment by ghutchis** [comment]
I'm closing this as we're not going to merge particular parsers. If you want a link-out, that's just fine. :-)

**Pull request closed without merging**
