### PR TITLE
Update opensmiles.asciidoc

### PR DESCRIPTION
**Pull request by philthiel**
Probably, 'atoms' are meant here?

### CODE REVIEW

**Comment by johnmay** [comment]
Thanks

**Comment by johnmay** [comment]
Reverted, just rebuilt the doc and read it in the context. It as meant to be hydrogens.

```[CH4]``` the hydrogens are not isotopes, ```[H]C([H])([H])[H]``` will canonicalize to the same whilst ```[2H]C([H])([H])[H]``` would not.

**Comment by ghutchis** [comment]
@johnmay Is there a write-up on generating the site from the asciidoc file?

**Comment by johnmay** [comment]
Should just need to type ```make```, there are a few dependencies IIRC:

```
$ brew install asciidoc
$ brew install xmlstarlet
$ pip install dblatex
```

I had some problems with dblatex and just installed in manually in the end. You obviously need MacTex before installing that too.

**Pull request merged**
